application: libraryappointment
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: site/index.html
  upload: site/index.html

- url: /(.*\.(gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff))
  static_files: site/\1
  upload: site/(.*\.(gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff))

libraries:
- name: webapp2
  version: "2.5.2"
